### ISSUE TITLE
stop-cluster, terminate-cluster broken

### ISSUE THREAD

**Issue by adderan** [BD2KGenomics/cgcloud#99]
```
Traceback (most recent call last):
  File "/home/alden/cgcloud/env/bin/cgcloud", line 9, in <module>
    load_entry_point('cgcloud-core==1.4a1.dev0', 'console_scripts', 'cgcloud')()
  File "/home/alden/cgcloud/core/src/cgcloud/core/cli.py", line 49, in main
    app.run( args )
  File "/home/alden/cgcloud/lib/src/cgcloud/lib/util.py", line 306, in run
    command.run( options )
  File "/home/alden/cgcloud/core/src/cgcloud/core/commands.py", line 81, in run
    return self.run_in_ctx( options, ctx )
  File "/home/alden/cgcloud/core/src/cgcloud/core/cluster_commands.py", line 45, in run_in_ctx
    self.run_on_cluster_type( ctx, options, cluster_type )
  File "/home/alden/cgcloud/core/src/cgcloud/core/cluster_commands.py", line 175, in run_on_cluster_type
    self.run_on_cluster( options, ctx, cluster )
  File "/home/alden/cgcloud/core/src/cgcloud/core/cluster_commands.py", line 296, in run_on_cluster
    pool_size=min(options.num_threads),
TypeError: 'int' object is not iterable
```

Should this be min(options.num_threads, options.num_workers)?

**Comment by hannes-ucsc** [comment]
I think I fixed this already. What branch are you on?

**Comment by adderan** [comment]
I'm on master, because I use the grow-cluster command. It looks like the problem is still there: https://github.com/BD2KGenomics/cgcloud/blob/master/core/src/cgcloud/core/cluster_commands.py#L296

**Comment by hannes-ucsc** [comment]
Can you try the scalability-fixes branch? It's in fairly good shape right now, probably better than master.

**Comment by hannes-ucsc** [comment]
... but I do force push to that branch so don't base any work on it.
